### PR TITLE
Use postcss-url plugin

### LINKED ISSUE #215: Assets in .css files are breaking formidable-charts-docs
Using a relative path (e.g. `background: url("../../static/hero.png;")` causes the `build-static` task to break in `formidable-charts-docs`, whereas an absolute path does not (e.g. `background: url("/static/hero.png;")`. Unfortunately this particular file in question is not small enough to be a data uri, which means the absolute path breaks in production: `/static/hero.png` does not exist, as the path should be `/open-source/victory/static/hero.png`.

Not sure how to resolve it yet—maybe a different webpack loader? maybe need a different postcss plugin to import `.png` (like how we’re using `postcss-inline-svg` for `.svg` files)? I recently read `css-loader` should be using `require()` to resolve the path name, but webpack can’t find it when it’s being pulled in as a dependency is my current theory

Error: https://travis-ci.org/FormidableLabs/formidable-charts-docs/jobs/175266161#L1682

```
modulesModuleNotFoundError: Module not found: Error: Cannot resolve 'file' or 
'directory' ../../static/hero@2x.png in 
/home/travis/build/FormidableLabs/formidable-charts-docs/src/styles
```

### PR DESCRIPTION
**Pull request by exogen**
Along with some relative path updates, seems to fix FormidableLabs/victory-docs#215.

/cc @paulathevalley @ryan-roemer

### CODE REVIEW

**Comment by ryan-roemer** [comment]
Great work @exogen !!! LGTM

**Comment by paulathevalley** [comment]
:rocket:

**Comment by exogen** [comment]
We probably want this to be a MAJOR bump even though it fixes stuff, since it changes `url()` handling. Thoughts @paulathevalley @ryan-roemer?

**Comment by exogen** [comment]
```
+ builder-docs-archetype@5.0.0
+ builder-docs-archetype-dev@5.0.0
```

**Pull request merged**
