### PR TITLE
Add default `navigator.userAgent` value

### PR DESCRIPTION
**Pull request by coopy**
Work around https://github.com/FormidableLabs/radium/issues/822

/cc @bmathews @ebrillhart @paulathevalley

### CODE REVIEW

**Comment by bmathews** [comment]
:shipit:

**Comment by coopy** [comment]
When linking this to `formidable-playbook-docs` and running `builder run build-static` I get

```
Error: Source file not found: "main"
```

Longer version:

```
[builder:builder-core:start:72265] Started: run webpack-static
[builder:run] webpack-static - webpack --config node_modules/builder-docs-archetype/config/webpack/webpack.config.static.js --progress --bail
[builder:proc:start] Command: webpack --config node_modules/builder-docs-archetype/config/webpack/webpack.config.static.js --progress --bail
 95% emit

ChunkRenderError: No template for dependency: TemplateArgumentDependency
    at Compilation.createChunkAssets (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compilation.js:874:21)
    at Compilation.<anonymous> (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compilation.js:557:8)
    at Compilation.applyPluginsAsync (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.seal (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compilation.js:525:7)
    at Compiler.<anonymous> (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compiler.js:397:15)
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/tapable/lib/Tapable.js:103:11
    at Compilation.<anonymous> (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compilation.js:445:10)
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compilation.js:417:12
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compilation.js:332:10
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/async/lib/async.js:52:16
    at done (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/async/lib/async.js:246:17)
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/async/lib/async.js:44:16
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compilation.js:332:10
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/async/lib/async.js:52:16
    at done (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/async/lib/async.js:246:17)
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/async/lib/async.js:44:16
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compilation.js:332:10
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/async/lib/async.js:52:16
    at done (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/async/lib/async.js:246:17)
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/async/lib/async.js:44:16
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compilation.js:332:10
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/async/lib/async.js:52:16
    at done (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/async/lib/async.js:246:17)
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/async/lib/async.js:44:16
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compilation.js:332:10
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/async/lib/async.js:52:16
    at done (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/async/lib/async.js:246:17)
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/async/lib/async.js:44:16
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compilation.js:332:10
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/async/lib/async.js:52:16


Error: Source file not found: "main"
    at Compiler.<anonymous> (/Users/per/dev/formidable/builder-docs-archetype/node_modules/static-site-generator-webpack-plugin/index.js:25:15)
    at Compiler.next (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/tapable/lib/Tapable.js:69:14)
    at Compiler.<anonymous> (/Users/per/dev/formidable/builder-docs-archetype/node_modules/webpack-stats-plugin/lib/stats-writer-plugin.js:75:5)
    at Compiler.applyPluginsAsync (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.emitAssets (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compiler.js:226:7)
    at Compiler.<anonymous> (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compiler.js:184:10)
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compiler.js:403:12
    at Compiler.next (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/tapable/lib/Tapable.js:67:11)
    at Compiler.<anonymous> (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.<anonymous> (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compiler.js:400:9)
    at Compilation.<anonymous> (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compilation.js:577:13)
    at Compilation.next (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/tapable/lib/Tapable.js:67:11)
    at Compilation.<anonymous> (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/ProgressPlugin.js:69:5)
    at Compilation.applyPluginsAsync (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.<anonymous> (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compilation.js:572:10)
    at Compilation.next (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/tapable/lib/Tapable.js:67:11)
    at Compilation.<anonymous> (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/ProgressPlugin.js:65:5)
    at Compilation.next (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/tapable/lib/Tapable.js:69:14)
    at Compilation.<anonymous> (/Users/per/dev/formidable/builder-docs-archetype/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:137:4)
    at Compilation.applyPluginsAsync (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.<anonymous> (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compilation.js:567:9)
    at Compilation.applyPluginsAsync (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compilation.js:563:8)
    at Compilation.applyPluginsAsync (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.seal (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compilation.js:525:7)
    at Compiler.<anonymous> (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compiler.js:397:15)
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/tapable/lib/Tapable.js:103:11
    at Compilation.<anonymous> (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compilation.js:445:10)
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compilation.js:417:12
[builder:proc:end:1] Command: webpack --config node_modules/builder-docs-archetype/config/webpack/webpack.config.static.js --progress --bail
[builder:builder-core:end:72265] Task: run webpack-static, Error: Command failed: webpack --config node_modules/builder-docs-archetype/config/webpack/webpack.config.static.js --progress --bail
 51% 68/99 build[builder:proc:end:1] Command: builder run clean-static && builder run update-project && builder run webpack-static && builder run copy-assets
[builder:builder-core:end:72134] Task: run build-static, Error: Command failed: builder run clean-static && builder run update-project && builder run webpack-static && builder run copy-assets
npm WARN skippingAction Module is inside a symlinked module: not running remove history@2.1.2 node_modules/formidable-playbook/node_modules/history
npm WARN skippingAction Module is inside a symlinked module: not running remove lodash@4.15.0 node_modules/formidable-playbook/node_modules/lodash
npm WARN skippingAction Module is inside a symlinked module: not running remove babel-preset-stage-1@6.13.0 node_modules/formidable-playbook/node_modules/babel-preset-stage-1
npm WARN skippingAction Module is inside a symlinked module: not running remove react@15.2.1 node_modules/formidable-playbook/node_modules/react
npm WARN skippingAction Module is inside a symlinked module: not running remove rimraf@2.5.4 node_modules/formidable-playbook/node_modules/rimraf
npm WARN skippingAction Module is inside a symlinked module: not running remove builder@2.10.1 node_modules/formidable-playbook/node_modules/builder
npm WARN skippingAction Module is inside a symlinked module: not running remove builder-docs-archetype@3.0.2 node_modules/formidable-playbook/node_modules/builder-docs-archetype
npm WARN skippingAction Module is inside a symlinked module: not running remove builder-docs-archetype-dev@3.0.2 node_modules/formidable-playbook/node_modules/builder-docs-archetype-dev
npm WARN skippingAction Module is inside a symlinked module: not running remove color@0.11.3 node_modules/formidable-playbook/node_modules/color
npm WARN skippingAction Module is inside a symlinked module: not running remove doctoc@1.2.0 node_modules/formidable-playbook/node_modules/doctoc
npm WARN skippingAction Module is inside a symlinked module: not running remove formidable-landers@3.4.1 node_modules/formidable-playbook/node_modules/formidable-landers
npm WARN skippingAction Module is inside a symlinked module: not running remove http-server@0.9.0 node_modules/formidable-playbook/node_modules/http-server
npm WARN skippingAction Module is inside a symlinked module: not running remove markdown-it@7.0.1 node_modules/formidable-playbook/node_modules/markdown-it
npm WARN skippingAction Module is inside a symlinked module: not running remove markdown-it-named-headers@0.0.4 node_modules/formidable-playbook/node_modules/markdown-it-named-headers
npm WARN skippingAction Module is inside a symlinked module: not running remove radium@0.18.1 node_modules/formidable-playbook/node_modules/radium
npm WARN skippingAction Module is inside a symlinked module: not running remove react-dom@15.2.1 node_modules/formidable-playbook/node_modules/react-dom
npm WARN skippingAction Module is inside a symlinked module: not running remove react-ga@2.1.1 node_modules/formidable-playbook/node_modules/react-ga
npm WARN skippingAction Module is inside a symlinked module: not running remove react-router@2.7.0 node_modules/formidable-playbook/node_modules/react-router
npm WARN skippingAction Module is inside a symlinked module: not running remove webpack@1.13.2 node_modules/formidable-playbook/node_modules/webpack
npm WARN update-linked node_modules/formidable-playbook needs updating to 0.0.3 from 0.0.1 but we can't, as it's a symlink
 95% emit

ChunkRenderError: No template for dependency: TemplateArgumentDependency
    at Compilation.createChunkAssets (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compilation.js:874:21)
    at Compilation.<anonymous> (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compilation.js:557:8)
    at Compilation.applyPluginsAsync (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.seal (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compilation.js:525:7)
    at Compiler.<anonymous> (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compiler.js:397:15)
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/tapable/lib/Tapable.js:103:11
    at Compilation.<anonymous> (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compilation.js:445:10)
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compilation.js:417:12
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compilation.js:332:10
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/async/lib/async.js:52:16
    at done (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/async/lib/async.js:246:17)
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/async/lib/async.js:44:16
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compilation.js:332:10
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/async/lib/async.js:52:16
    at done (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/async/lib/async.js:246:17)
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/async/lib/async.js:44:16
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compilation.js:332:10
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/async/lib/async.js:52:16
    at done (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/async/lib/async.js:246:17)
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/async/lib/async.js:44:16
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compilation.js:332:10
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/async/lib/async.js:52:16
    at done (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/async/lib/async.js:246:17)
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/async/lib/async.js:44:16
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compilation.js:332:10
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/async/lib/async.js:52:16
    at done (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/async/lib/async.js:246:17)
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/async/lib/async.js:44:16
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compilation.js:332:10
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/async/lib/async.js:52:16


Error: Source file not found: "main"
    at Compiler.<anonymous> (/Users/per/dev/formidable/builder-docs-archetype/node_modules/static-site-generator-webpack-plugin/index.js:25:15)
    at Compiler.next (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/tapable/lib/Tapable.js:69:14)
    at Compiler.<anonymous> (/Users/per/dev/formidable/builder-docs-archetype/node_modules/webpack-stats-plugin/lib/stats-writer-plugin.js:75:5)
    at Compiler.applyPluginsAsync (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.emitAssets (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compiler.js:226:7)
    at Compiler.<anonymous> (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compiler.js:184:10)
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compiler.js:403:12
    at Compiler.next (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/tapable/lib/Tapable.js:67:11)
    at Compiler.<anonymous> (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.<anonymous> (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compiler.js:400:9)
    at Compilation.<anonymous> (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compilation.js:577:13)
    at Compilation.next (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/tapable/lib/Tapable.js:67:11)
    at Compilation.<anonymous> (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/ProgressPlugin.js:69:5)
    at Compilation.applyPluginsAsync (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.<anonymous> (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compilation.js:572:10)
    at Compilation.next (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/tapable/lib/Tapable.js:67:11)
    at Compilation.<anonymous> (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/ProgressPlugin.js:65:5)
    at Compilation.next (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/tapable/lib/Tapable.js:69:14)
    at Compilation.<anonymous> (/Users/per/dev/formidable/builder-docs-archetype/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:137:4)
    at Compilation.applyPluginsAsync (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.<anonymous> (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compilation.js:567:9)
    at Compilation.applyPluginsAsync (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compilation.js:563:8)
    at Compilation.applyPluginsAsync (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.seal (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compilation.js:525:7)
    at Compiler.<anonymous> (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compiler.js:397:15)
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/tapable/lib/Tapable.js:103:11
    at Compilation.<anonymous> (/Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compilation.js:445:10)
    at /Users/per/dev/formidable/playbook/formidable-playbook-docs/node_modules/webpack/lib/Compilation.js:417:12
[builder:proc:end:1] Command: webpack --config node_modules/builder-docs-archetype/config/webpack/webpack.config.static.js --progress --bail
[builder:builder-core:end:72265] Task: run webpack-static, Error: Command failed: webpack --config node_modules/builder-docs-archetype/config/webpack/webpack.config.static.js --pro
```

**Comment by coopy** [comment]
It's because of [duplicate webpack versions](https://github.com/webpack/webpack/issues/1082)

```
~/dev/formidable/playbook/formidable-playbook-docs (bug-fixHeaderFontWeights)$ npm ls webpack
formidable-playbook-lander@0.0.1 /Users/per/dev/formidable/playbook/formidable-playbook-docs
├─┬ builder-docs-archetype@3.0.2 -> /Users/per/dev/formidable/builder-docs-archetype
│ └── webpack@1.12.9
├─┬ formidable-playbook@0.0.1 -> /Users/per/dev/formidable/playbook/formidable-playbook invalid
│ └── webpack@1.13.2  extraneous
└── webpack@1.12.9  extraneous
```

**Comment by coopy** [comment]
Thinking about making this a major-version release since I really don't know whether webpack 1.13 poses a problem for some dependent projects.

https://github.com/webpack/docs/wiki/changelog#113

> - ES6 parser support backported from webpack 2

**Comment by philiptzou** [comment]
Actually I don't think this is a good fix. I used https://github.com/markdalgleish/static-site-generator-webpack-plugin to generate static pages server-sidely. Since the generated html pages will be served for every browser the webpack and Radium can not know which browser the client used. A best fix to me is to generate something like this if `userAgent="all"` instead flatten the array or do anything else:

``` css
xxx {
  display: -webkit-box;
  display: -moz-box;
  display: -ms-flexbox;
  display:  -webkit-flex;
  display:  flex
}
```

**Pull request merged**
