### PR TITLE
Add eslint-plugin-import, update eslint

### LINKED ISSUE #110: Add eslint-plugin-import
To all the projects! https://www.npmjs.com/package/eslint-plugin-import

### PR DESCRIPTION
**Pull request by kylecesmat**
Will close https://github.com/FormidableLabs/formidable-landers/issues/110

### CODE REVIEW

**Comment by kylecesmat** [comment]
~~This will depend on https://github.com/walmartlabs/eslint-config-defaults/issues/76 and https://github.com/walmartlabs/eslint-config-defaults/issues/77 being resolved~~

Will update to depend on https://github.com/walmartlabs/eslint-config-walmart

**Comment by ryan-roemer** [comment]
@kylecesmat -- `eslint-config-defaults` is going to be deprecated. Please focus instead on upgrading to https://github.com/walmartlabs/eslint-config-walmart and tackling the issues there.

@baer @exogen -- Can you guys help @kylecesmat get the necessary stuff fixed in https://github.com/walmartlabs/eslint-config-walmart?

**Comment by kylecesmat** [comment]
@baer @exogen - is `eslint-config-walmart` published on npm yet? It doesn't appear to be in the registry

**Comment by kylecesmat** [comment]
Closing this PR due to inactivity.

**Comment by chrismcleod** [comment]
anyone who noticed eslint-config-walmart not in npm registry, github packages can be installed like:
npm i -g walmartlabs/eslint-config-walmart

**Pull request closed without merging**
